name: 'Roblox-README-Puller'
description: 'Auto-update your README with your Roblox Avatar and profile details'
inputs:
  roblox_user_id:
    description: 'Roblox User ID (numeric)'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install requests
      shell: bash
    - run: python ${{ github.action_path }}/update_roblox.py
      shell: bash
      env:
        ROBLOX_USER_ID: ${{ inputs.roblox_user_id }}
